-- =============================================
-- MASTER_CATALOG: Danh mục master data
-- =============================================

CREATE TABLE MASTER_CATALOG (
    ID          VARCHAR2(50)  PRIMARY KEY,
    NAME        NVARCHAR2(255) NOT NULL,
    PARENT_ID   VARCHAR2(50)  REFERENCES MASTER_CATALOG(ID),
    NOTE        NVARCHAR2(100),
    TYPE        VARCHAR2(50)  NOT NULL,
    SORT_ORDER  NUMBER(10)    DEFAULT 0,
    ACTIVE      NUMBER(1)     DEFAULT 1 NOT NULL,
    CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP,
    UPDATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_CATALOG_TYPE ON MASTER_CATALOG(TYPE);
CREATE INDEX IDX_CATALOG_PARENT ON MASTER_CATALOG(PARENT_ID);

-- Nhóm I: Tổng EVNNPC tạm tính
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('EVNNPC', 'Tổng EVNNPC tạm tính', NULL, 'I', 'ORGANIZATION', 1);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('NPCNG', 'Theo NG (Ngân sách/Nguồn)', 'EVNNPC', '1', 'ORGANIZATION', 2);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('NPCTK10', 'Định mức tiết kiệm 10%', 'EVNNPC', '2', 'ORGANIZATION', 3);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('NPCTK30', 'Định mức tiết kiệm 30%', 'EVNNPC', '3', 'ORGANIZATION', 4);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('NPCDP', 'Dự phòng', 'EVNNPC', '4', 'ORGANIZATION', 5);

-- Nhóm II: Các Công ty TNHH MTV
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('GRP_MTV', 'CÁC CÔNG TY TNHH MTV', NULL, 'II', 'ORGANIZATION', 6);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCHP', 'TNHH MTV Điện lực Hải Phòng', 'GRP_MTV', '1', 'ORGANIZATION', 7);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCHD', 'TNHH MTV Điện lực Hải Dương', 'GRP_MTV', '2', 'ORGANIZATION', 8);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCNB', 'TNHH MTV Điện lực Ninh Bình', 'GRP_MTV', '3', 'ORGANIZATION', 9);

-- Nhóm III: Các Đơn vị Phụ trợ
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('GRP_AUX', 'CÁC ĐƠN VỊ PHỤ TRỢ', NULL, 'III', 'ORGANIZATION', 10);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('NPC_VP', 'Văn phòng cơ quan', 'GRP_AUX', '4', 'ORGANIZATION', 11);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('NPCIT', 'Công ty CNTT ĐL miền Bắc', 'GRP_AUX', '5', 'ORGANIZATION', 12);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('NPCCC', 'Trung tâm CSKH', 'GRP_AUX', '6', 'ORGANIZATION', 13);

-- Nhóm IV: Các Công ty Điện lực
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('GRP_PC', 'CÁC CÔNG TY ĐIỆN LỰC', NULL, 'IV', 'ORGANIZATION', 14);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCND', 'Công ty Điện lực Nam Định', 'GRP_PC', '8', 'ORGANIZATION', 15);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCPT', 'Công ty Điện lực Phú Thọ', 'GRP_PC', '9', 'ORGANIZATION', 16);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCQN', 'Công ty Điện lực Quảng Ninh', 'GRP_PC', '10', 'ORGANIZATION', 17);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCTN', 'Công ty Điện lực Thái Nguyên', 'GRP_PC', '11', 'ORGANIZATION', 18);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCBG', 'Công ty Điện lực Bắc Giang', 'GRP_PC', '12', 'ORGANIZATION', 19);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCTH', 'Công ty Điện lực Thanh Hóa', 'GRP_PC', '13', 'ORGANIZATION', 20);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCTB', 'Công ty Điện lực Thái Bình', 'GRP_PC', '14', 'ORGANIZATION', 21);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCYB', 'Công ty Điện lực Yên Bái', 'GRP_PC', '15', 'ORGANIZATION', 22);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCLS', 'Công ty Điện lực Lạng Sơn', 'GRP_PC', '16', 'ORGANIZATION', 23);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCTQ', 'Công ty Điện lực Tuyên Quang', 'GRP_PC', '17', 'ORGANIZATION', 24);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCNA', 'Công ty Điện lực Nghệ An', 'GRP_PC', '18', 'ORGANIZATION', 25);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCCB', 'Công ty Điện lực Cao Bằng', 'GRP_PC', '19', 'ORGANIZATION', 26);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCSL', 'Công ty Điện lực Sơn La', 'GRP_PC', '20', 'ORGANIZATION', 27);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCHT', 'Công ty Điện lực Hà Tĩnh', 'GRP_PC', '21', 'ORGANIZATION', 28);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCHB', 'Công ty Điện lực Hòa Bình', 'GRP_PC', '22', 'ORGANIZATION', 29);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCLC', 'Công ty Điện lực Lào Cai', 'GRP_PC', '23', 'ORGANIZATION', 30);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCDB', 'Công ty Điện lực Điện Biên', 'GRP_PC', '24', 'ORGANIZATION', 31);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCHG', 'Công ty Điện lực Hà Giang', 'GRP_PC', '25', 'ORGANIZATION', 32);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCBN', 'Công ty Điện lực Bắc Ninh', 'GRP_PC', '26', 'ORGANIZATION', 33);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCHY', 'Công ty Điện lực Hưng Yên', 'GRP_PC', '27', 'ORGANIZATION', 34);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCHN', 'Công ty Điện lực Hà Nam', 'GRP_PC', '28', 'ORGANIZATION', 35);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCVP', 'Công ty Điện lực Vĩnh Phúc', 'GRP_PC', '29', 'ORGANIZATION', 36);
INSERT INTO MASTER_CATALOG (ID, NAME, PARENT_ID, NOTE, TYPE, SORT_ORDER) VALUES ('PCBK', 'Công ty Điện lực Bắc Kạn', 'GRP_PC', '30', 'ORGANIZATION', 37);

COMMIT;
